language: node_js
notifications:
node_js:
- 6.10.3
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp
before_install:
- npm install -g npm@5.6.0
script:
- source read.version.sh
- echo $PACKAGE_JSON_VERSION
- npm run minimize
- npm test
branches:
  only:
  - master
  - "/^.*release.*$/1"
  - "/2\\.[0-9]+\\.[0-9]+/"