language: node_js
notifications:
node_js:
- 6.10.3
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp
before_install:
- npm install -g npm@5.6.0
script:
- source read.version.sh
- echo $PACKAGE_JSON_VERSION
- npm run minimize
- npm run test
after_success:
# - npm run doc
# - if [ "x$TRAVIS_TAG" != "x" ]; then bash ./deploy.doc.sh ; fi
# - npm run docsitemap
# - npm run zipForGitReleases
branches:
  only:
  - light-cli