Organization
  name: myuatorg
  Sources
    Source
    - name: MySource
    - Overrides
      - baseUrl: http://uat.mywebsite.com
      - username: uatuser
Organization
  name: myprodorg
  Sources
      Source
      - name: MySource
      - Overrides
        - name: MyProdSource
        - baseUrl: http://prod.mywebsite.com
        - username: produser